#!/bin/bash

# Variables
SESSION_NAME="Know-your-stats_services"   # Change the session name if needed

# Check if the tmux session already exists
tmux has-session -t $SESSION_NAME 2>/dev/null

# If the session does not exist, create a new one
if [ $? != 0 ]; then
  echo "Creating new tmux session: $SESSION_NAME"
  tmux new-session -d -s $SESSION_NAME  # Create new session

  tmux split-window -h

  tmux send-keys -t 0 'npm run dev' C-m
  tmux send-keys -t 1 'z client'
  tmux send-keys -t 1 'npm run start' C-m
fi

# Attach to the tmux session
tmux attach-session -t $SESSION_NAME