
### Sanity check
# http://localhost:3001/api
GET http://localhost:3001/api

### Get all stopwatches
# http://localhost:3001/api/stopwatches
GET http://localhost:3001/api/stopwatches

### Add a new stopwatch
# http://localhost:3001/api/stopwatches
POST http://localhost:3001/api/stopwatches
content-type: application/json

{
    "name": "Stopwatch 3",
    "description": "Stopwatch 3 description"
}

### Rename a stopwatch of provided id
# http://localhost:3001/api/stopwatches/:id
PUT http://localhost:3001/api/stopwatches/2
content-type: application/json

{
    "name": "Renamed Stopwatch 2"
}

### Delete a stopwatch of provided id and all its entries
# http://localhost:3001/api/stopwatches/:id
DELETE http://localhost:3001/api/stopwatches/1

### Get n entries for a stopwatch of provided id
# http://localhost:3001/api/stopwatches/:id/entries/:n
GET http://localhost:3001/api/stopwatches/3/entries/5

### Add a new stopwatch entry only if its not running
# http://localhost:3001/api/stopwatches/:id/entries
POST http://localhost:3001/api/stopwatches/4/entries
content-type: application/json

{
    "start_time": "2021-09-01T12:00:00.000Z"
}

### Update the last stopwatch entry only if its running
# http://localhost:3001/api/stopwatches/:id/entries
PUT http://localhost:3001/api/stopwatches/4/entries
content-type: application/json

{
    "stop_time": "2021-09-01T14:00:00.000Z"
}

### Delete stopwatch entry of provided id
# http://localhost:3001/api/stopwatches/entries/:entry_id
DELETE http://localhost:3001/api/stopwatches/entries/4

### Login
# http://localhost:3001/api/auth/login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "username": "franek",
    "password": "letmein"
}